### ISSUE TITLE
It will not let me install vcredist_x64.exe or vcredist_x86.exeon newer version of Microsoft Visual C++

### ISSUE THREAD

**Issue by xam33r** [acrcloud/acrcloud_sdk_java#1]
Is it possible to provide a release which will be install-able on on system having updated versions of Microsoft Visual C++

or any other fix.

**Comment by qiuxuewen** [comment]
You can download Microsoft C++ library from (https://www.microsoft.com/en-us/download/details.aspx?id=5555  or https://www.microsoft.com/en-us/download/details.aspx?id=14632).
If you have installed it, and retry ACRCloud SDK. If have any other problems,  please send me the error details.
Thank  You.

**Comment by rajan00** [comment]
No matter whether you’re on Windows 7 or the newest Windows 10, your computer will start slowing down with time.You can easily access the all things from here [https://unfitpc.com/vcredist_x64-exe](https://unfitpc.com/vcredist_x64-exe)  Luckily, there’s no need to panic because you can easily make Windows faster again without the help of a technician or any expensive software.
